prefapp/formacion

cursos/docker-images/01_creacion_de_imaxes/05_o_dockerfile_construindo_a_imaxe_do_gatinho_do_dia.md
Change pip version in gatiño do día
=> Change pip version in gatiño do día

cursos/docker/04_aplicacions_e_servizos_multicontedor/08_practica_guiada_nesquik_vs_colacao.md
Se han cambiado algunos valores del docker-compose que estaban mal.
=> Cambiar imágenes fallidas

cursos/kubernetes/02_kubernetes/02_arquitectura_kubernetes.md, cursos/kubernetes/02_kubernetes/03_arquitectura_kubernetes_pod.md, cursos/kubernetes/02_kubernetes/05_arquitectura_kubernetes_service.md, cursos/kubernetes/03_configuracion/01_Configuracions_en_Kubernetes.md, cursos/kubernetes/03_configuracion/02_Controlando_os_pods.md
=> Added missing info

cursos/docker/00_actividades/01_modulo_1.md, cursos/docker/00_actividades/02_modulo_2.md, cursos/kubernetes/00_actividades/01_modulo_1.md, cursos/kubernetes/00_actividades/02_modulo_2.md, cursos/kubernetes/00_actividades/03_modulo_3.md, cursos/kubernetes/03_configuracion/01_Configuracions_en_Kubernetes.md, cursos/kubernetes/03_configuracion/02_Controlando_os_pods.md, cursos/kubernetes/03_configuracion/03_Persistencia_en_K8s.md
Updated a pair of missing links, bunch of typos, some headers, etc
=> Various maintenance fixes (links, typos, images...)

cursos/kubernetes/00_actividades/03_modulo_3.md, cursos/kubernetes/03_configuracion/06_Helm.md
Added a link and fixed a image
=> Fixed an image and a link was added

cursos/docker-images/index.html, cursos/docker/index.html, cursos/kubernetes/index.html
Cambiar descripción y ruta favicon
=> Cambiar descripción y ruta favicon

cursos/docker/00_actividades/05_modulo_5.md, cursos/docker/_sidebar.md
=> correccion nombre fichero en _sidebar

cursos/kubernetes/02_kubernetes/01_que_e_kubernetes.md
Changing deaths urls for a new article
=> Fix death urls

cursos/kubernetes/03_configuracion/04_Namespaces_usuarios_e_roles.md
=> Add info about namespaces creation

cursos/helm/02_helm_charts/04_practica_guiada_2.md
configmap missconfigured in guided practice nº2
=> add info configmap chahpter helm guided practice#2

cursos/docker/04_creacion_de_imaxes/06_mellorando_o_dockerfile_de_web_gatinho_do_dia.md
Changed dockerfile to use Ubuntu 20.04 and Python3.
Closes #95
=> Correct Dockerfile to run latest web-gatinhos

cursos/docker/00_actividades/01_modulo_1.md, cursos/docker/01_que_e_un_contedor_de_software/05_solucion_completa_2.md, cursos/docker/01_que_e_un_contedor_de_software/09_cgroups_xestion_e_utilidades.md
Update cgroup information with changes from v2.
=> Add cgroupv2 updates

curso-base/index.html, cursos/docker-images/index.html, cursos/docker/index.html, cursos/helm/index.html, cursos/kubernetes/index.html, index.html
=> Add mermaid to all courses

cursos/docker/00_actividades/06_modulo_6.md
Add Traefik guide to Swarm practice
=> Add Traefik guide to Swarm practice

cursos/kubernetes/03_configuracion/11_Assigning_Pods_to_Nodes.md, cursos/kubernetes/_sidebar.md, cursos/kubernetes/es/03_configuracion/11_Assigning_Pods_to_Nodes.md, cursos/kubernetes/es/_sidebar.md
closes #120 
I have made this PR starting from the current master branch so that it can be added before the PRs that are on hold (#116, #117, #118 and #119), I hope it will not cause conflicts later.
closes
=> Add spanish file 11_Assigning_Pods_to_Nodes.md in k8s

cursos/kubernetes/03_configuracion/11_Assigning_Pods_to_Nodes.md
=> Upgrades in 11_Assigning_Pods_to_Nodes.md

cursos/kubernetes/es/00_actividades/03_modulo_3.md, cursos/kubernetes/es/03_configuracion/02_Controlando_os_pods.md
I found some more errors in the translation of the Kubernetes course. They are minutiae.
=> translation corrections kubernetes course

cursos/docker/00_actividades/01_modulo_1.md
Updated cpu cgroup task description so it references the correct parameter the user should update
=> Updated modulo_01

cursos/docker/es/00_actividades/01_modulo_1.md
Updated the description of the cpu cgroup task in version "es" to refer to the correct parameter.
[PR](https://github.com/prefapp/formacion/pull/130) in Galician.
=> Updated modulo_01 es

cursos/docker/04_creacion_de_imaxes/05_o_dockerfile_construindo_a_imaxe_do_gatinho_do_dia.md, cursos/docker/es/04_creacion_de_imaxes/05_o_dockerfile_construindo_a_imaxe_do_gatinho_do_dia.md
=> Fix "gatinho do día" docs

cursos/docker-images/index.html, cursos/docker/index.html, cursos/helm/index.html, cursos/kubernetes/index.html, cursos/terraform/index.html
=> Added dark mode to all courses

cursos/docker/es/index.html, cursos/kubernetes/es/index.html, cursos/terraform/es/index.html
Added dark mode to spanish courses
=> Added dark mode to spanish courses

curso-base/index.html, cursos/docker-images/index.html, cursos/docker/es/index.html, cursos/docker/index.html, cursos/helm/index.html, cursos/kubernetes/es/index.html, cursos/kubernetes/index.html, cursos/terraform/es/index.html, cursos/terraform/index.html
I have changed the script
```
<script src="//unpkg.com/mermaid/dist/mermaid.js"></script>
<script src="//unpkg.com/docsify-mermaid@latest/dist/docsify-mermaid.js"></script>
<script>mermaid.initialize({ startOnLoad: true });</script>
<script>
mermaid.initialize({
startOnLoad: true,
securityLevel: 'loose',
logLevel: 1
});
</script>
```
to 
```
<script type="module">
import mermaid from "https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs";
mermaid.initialize({ startOnLoad: true });
window.mermaid = mermaid;
</script>
<script src="//unpkg.com/docsify-mermaid@2.0.0/dist/docsify-mermaid.js"></script>
```
in all index.html. As I have seen in the [documentation](https://github.com/Leward/mermaid-docsify)
=> Update mermaid module

cursos/kubernetes/03_configuracion/07_Helm.md
Fix command to install repos helm bitnami
=> Fix command to install repos helm bitnami

cursos/kubernetes/03_configuracion/11_Assigning_Pods_to_Nodes.md
In this .yaml there is a missing enter.
=> Correcting a mistake

cursos/kubernetes/03_configuracion/08_Adaptandose_as_demandas.md
The previous link does not work anymore, I changed it for the new one.
=> Changing a link that does not work anymore

cursos/kubernetes/03_configuracion/12_practica_guiada_assing_pods_to_nodes.md
In these cases it's not the first yaml, i'ts the second one.
=> Fixing an error in a command

cursos/helm/00_actividades/02_modulo_2.md, cursos/helm/00_solucions/helm_wordpress/templates/ingress.yaml, cursos/helm/02_helm_charts/04_practica_guiada_2.md, cursos/helm/index.html
=> 167 helm links fail

cursos/helm/00_actividades/02_modulo_2.md
The original link show a 404 error on the formation page. I changed it.
=> Fixing link

cursos/helm/02_helm_charts/04_practica_guiada_2.md
it's not the beta version anymore, now it's just v1
=> Changing old version for a newer one

cursos/terraform/01_terraform/06_practica_guiada.md
Fixing the indentation of this script.
=> Fixing indentation in script

cursos/terraform/01_terraform/05_practica_guiada.md
- Changing the version from 3.0 to 5.48.0
- Adding the necessary configuration to create a VPC
=> Adding configurations to the formation

cursos/terraform/01_terraform/05_practica_guiada.md
Updating the version of the aws provider
=> Updating version of the provider

index.html
I have noticed that the description of two of the new courses is too long, so it breaks the structure. I have fixed it so it fits the given space.
=> Change description of some courses

cursos/git/02_hands_on/05_Guided_practice-Cloning_repo_branch_creation_first_commit_pull_request.md, cursos/git/es/02_hands_on/05_Guided_practice-Cloning_repo_branch_creation_first_commit_pull_request.md, cursos/git/es/README.md
=> Center images & fix link

cursos/git/es/_coverpage.md
Fix previous commit: Optimise Git course images
=> Fix previous commit: Optimise Git course images

cursos/docker/04_creacion_de_imaxes/05_o_dockerfile_construindo_a_imaxe_do_gatinho_do_dia.md
Puntualizamos la versión de Ubuntu para evitar errores de construcción de imagen
=> gatinhos dockerfile
